In [2]:
#program to perform svd 
import numpy as num
from scipy.linalg import svd
b=num.array([[2,5,6],[8,9,1],[4,7,3]])
v,s,t=svd(b)
print("matrix into svd\n")
print(v)
print(s)
print(t)
print("\nsvd into matrix")
e=( v @ num.diag(s) @t)
print(e)

matrix into svd

[[-0.42540792  0.81454009 -0.39440149]
 [-0.73060838 -0.56628785 -0.38148325]
 [-0.53407817  0.12586704  0.83601316]]
[16.02030706  5.27693398  0.70973914]
[[-0.55130002 -0.77658076 -0.30494362]
 [-0.45438401 -0.02706513  0.89039466]
 [-0.6997167   0.6294361  -0.33794488]]

svd into matrix
[[2. 5. 6.]
 [8. 9. 1.]
 [4. 7. 3.]]
